STEP 13 contacts notes entitlement
bitrise-steplib/steps-ios-auto-provision-appstoreconnect pull request #31
Opened 2020-12-07 09:05 UTC by lpusok

2020-12-08 10:25 UTC, godrei requested changes

2020-12-08 10:25 UTC, godrei commented on appstoreconnect/appstoreconnect.go
> +		return nil, fmt.Errorf("parsing endpoint failed, %v", err)
please use `:` to separate the context from the error, like `parsing endpoint failed: %s` 

https://golang.org/doc/effective_go.html#errors

2020-12-08 10:25 UTC, godrei commented on appstoreconnect/capabilities.go
> +var UnsupportedEntitlements = []string{
for ignored (does not appear in profile) entitlements, we have a special type `Ignore`, see: https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/pull/31/files#diff-9e4f54818286790433c9c643f7f188562f0ae208f007cc141c8d8d0b22361e80R16

what about unifying this solution and adding a new type: `unsupported` and handle both similarly?

2020-12-08 10:25 UTC, godrei commented on main.go
> +	if err := autoprovision.ContainsUnsupportedEntitlement(entitlementsByBundleID, appstoreconnect.UnsupportedEntitlements); err != nil {
might it is better to suggest manually configuring the profile's unsupported entitlement, after that the step can work properly (as long as no new unsupported entitlements appear)

2020-12-08 10:41 UTC, mateherber commented on main.go
> +	if err := autoprovision.ContainsUnsupportedEntitlement(entitlementsByBundleID, appstoreconnect.UnsupportedEntitlements); err != nil {
Maybe we could list all not-supported entitlements as the error message

2020-12-09 14:51 UTC, godrei requested changes
pls check my notes

2020-12-09 14:51 UTC, godrei commented on autoprovision/entitlements_test.go
> +		want                   bool
pls use more descriptive properties, like `wantOk`, `wantEntitlement `, `wantBundleID `

2020-12-09 14:51 UTC, godrei commented on autoprovision/entitlements_test.go
> +			got, got1, got2 := autoprovision.CanGenerateProfileWithEntitlements(tt.entitlementsByBundleID)
pls use more descriptive vars, like `gotOk`, `gotEntitlement`, `gotBundleID`

2020-12-09 14:51 UTC, godrei commented on main.go
> +		log.Errorf("Can not create profile with unsupported entitlement (%s) for the bundle ID %s, due to API limitations.", entitlement, bundleID)
emphasize that it is not our service limitation: `due to API limitations` -> `due to App Store Connect API limitations`

2020-12-09 15:02 UTC, lpusok commented on main.go
> +	if err := autoprovision.ContainsUnsupportedEntitlement(entitlementsByBundleID, appstoreconnect.UnsupportedEntitlements); err != nil {
Discussed that we can not support this without sample app.

2020-12-09 15:02 UTC, lpusok commented on appstoreconnect/appstoreconnect.go
> +		return nil, fmt.Errorf("parsing endpoint failed, %v", err)
Done.

2020-12-09 15:02 UTC, lpusok commented on autoprovision/entitlements_test.go
> +		want                   bool
done

2020-12-09 15:02 UTC, lpusok commented on main.go
> +		log.Errorf("Can not create profile with unsupported entitlement (%s) for the bundle ID %s, due to API limitations.", entitlement, bundleID)
done

2020-12-09 15:14 UTC, godrei approved these changes

2020-12-09 15:25 UTC, merged

2020-12-09 17:20 UTC, petermnt commented
@lpusok  There is actually an undocumented way to create a provisioning profile with this special entitlement through the Appstore Connect api.
Fastlane has this implemented and this works for us. See https://github.com/fastlane/fastlane/blob/2624a24407dee94f67d7e39b5651f9fdc41dcb00/spaceship/lib/spaceship/connect_api/models/profile.rb#L83

The tricky thing is that this `templateName` is a very specific string that might not even be the same for every developer.
For us this is 
* CarPlay Audio App(Distribution)
* CarPlay Audio App(Distribution) (Adhoc)
* CarPlay Audio App(Develkopment)

Passing these to the API will create the correct provisioning profile.

Maybe `templateName` could be added as a configurable field in the bitrise step for people who need this?

2020-12-09 17:38 UTC, lpusok commented
@petermnt Checking, was not aware of this. How do you specifically look up the template name? In case I implement this, can you maybe help to validate that it works correctly?

2020-12-09 18:11 UTC, petermnt commented
@lpusok  The `templateName` works for creating new profiles.
The only way I know to look up the template name is to look manually in the developer portal.

There is a dropdown where you choose the special entitlement.
There can only be 1 per profile.

It looks like this:

<img width="536" alt="CleanShot 2020-12-09 at 19 10 53@2x" src="https://user-images.githubusercontent.com/698923/101669491-48521400-3a52-11eb-8e52-edfaa14d6868.png">

There is another thing to pay attention to, which is that (for us) in Adhoc configuration the visible value in the dropdown does not match the actual value:

```html
<select id="template" name="template"><option value="Standard">Default</option><option value="CarPlay Audio App(Distribution) (Adhoc)" selected="">CarPlay Audio App(Distribution)</option></select>
<option value="Standard">Default</option>
<option value="CarPlay Audio App(Distribution) (Adhoc)" selected="">CarPlay Audio App(Distribution)</option>
<select id="template" name="template"><option value="Standard">Default</option><option value="CarPlay Audio App(Distribution) (Adhoc)" selected="">CarPlay Audio App(Distribution)</option></select>
```

Passing the `value` `CarPlay Audio App(Distribution) (Adhoc)` to `templateName` creates the profile with this dropdown properly select.